Spread params into the context.bindingData
willmorgan/stub-azure-function-context pull request #42
Opened 2023-04-19 08:24 UTC by bartlomiejmont

relates to issue #41 

change overlap with how azure function works

2023-04-19 14:16 UTC, dhensby requested changes
just a minor change - thanks for this!

2023-04-19 14:16 UTC, dhensby commented on test/http-binding.spec.ts
> +        const functionStub = stub().resolves((context: Context) => context.bindingData);
```suggestion
        const functionStub = stub().resolve();
```

The stub shouldn't resolve to a function.

2023-04-19 14:41 UTC, bartlomiejmont commented on test/http-binding.spec.ts
> +        const functionStub = stub().resolves((context: Context) => context.bindingData);
Thanks ! changed :)

2023-04-20 09:09 UTC, dhensby approved these changes

2023-04-20 09:09 UTC, merged